# Configurations
title:            Grand Dub
longtitle:        Le blog de Grand Dub
author:           Grand Dub
# email:            sighingnow@gmail.com
description: Des notes sur mes connaissances en informatique

locale: fr_FR
lang: fr
social:
  name: Bruno Dubois
  links:
    - https://www.linkedin.com/in/bruno-dubois/
    - https://github.com/grand-dub

version:          1.0
gitbook_version:  3.2.3

tracker:
  google_analytics: G-J73RC3Z861

url:              'https://grand-dub.github.io'
baseurl:          '/blog'
rss:              RSS

# bootstrap: use the remote theme for the site itself
# remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

# syntax_highlighter_style: colorful
syntax_highlighter_style: github

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
#permalink:                /:categories/:year-:month-:day-:title:output_ext
permalink:                /:categories/:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

  - _drafts
  - README.md
  - LICENSE
  - '*.sh'
  - '*.bak'

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 90%

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  # - jekyll-readme-index
  - jemoji
  - jekyll-sitemap
